sudo: false
language: node_js
env: CI=true
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
after_script:
  - gulp coveralls
notifications:
  email: false
  slack:
    rooms:
      - generator-m-ionic:lZYXd9k3mcYBlsGUnd1xRb3R
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/87130ded51c12384d4e7
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
